apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xpartla/ambulance-ufe
    newName: xpartla/ambulance-ufe
    newTag: 1.1.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
  - name: xpartla/ambulance-wl-webapi
    newName: xpartla/ambulance-wl-webapi
    newTag: 1.0.2