apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital

secretGenerator:
  - name: repository-pat
    type: Opaque
    envs:
      - params/repository-pat.env
    options:
      disableNameSuffixHash: true
  - name: mongodb-auth
    type: Opaque
    envs:
      - params/mongodb-auth.env
    options:
      disableNameSuffixHash: true
  - name: oidc-client
    type: Opaque
    envs:
     - params/oidc-client.env
    options:
     disableNameSuffixHash: true
  - name: oidc-dex
    type: Opaque
    envs:
      - params/oidc-dex.env
    options:
      disableNameSuffixHash: true