apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xpartla/ambulance-ufe
    newName: xpartla/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20260316.1022 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
